networks:
  dev:
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - mynotes-frontend
      - mynotes-backend
    networks:
      - dev
  
  

  mynotes-frontend:
    build:
      context: ../frontend/my-notes
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - dev

  mynotes-backend:
    build:
      context: ./MyNotes
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=my_notes;User Id=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: my_notes
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
    postgres-data:
